### ISSUE TITLE
Add proper Novoda OS libs icons

### ISSUE THREAD

**Issue by xrigau** [novoda/image-loader#176] opened 2014-10-03 13:52 UTC
@ataulm said
 > The icons are wrong. @qqipp made some nice novoda OS lib ones that I'll add it again at some point. Once we have another lib, it'd be good to have different icons perhaps with the one Qi made as a base, so it's clear from a glance they're all from the same family but easy to tell them apart.

**Comment by friedger** [comment] 2015-01-27 16:15
@qqipp Where are these icons?

**Comment by qqipp** [comment] 2015-01-27 17:09
@friedger If these are the icons that you are looking for 
https://drive.google.com/a/novoda.com/folderview?id=0B-HQ4IohcR2kODVLWS1xLXFIU1U&usp=sharing

**Comment by friedger** [comment] 2015-01-27 17:22
@xrigau @ataulm Where is the place to put the icons?

**Comment by ataulm** [comment] 2015-01-27 17:25
It was intended to go on the play store demo, but no point updating it now.
Could just push it to the repo for now.
On 27 Jan 2015 17:22, "Friedger Müffke" <notifications@github.com> wrote:

> @xrigau <https://github.com/xrigau> @ataulm <https://github.com/ataulm>
> Where is the place to put the icons?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novoda/image-loader/issues/176#issuecomment-71688300>.
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by ataulm** [comment] 2015-01-30 10:46
fixed in https://github.com/novoda/image-loader/commit/9f0ce008c33724bbec4991fbee5ed7ecf51ddd95

**Closed by ataulm** 2015-01-30 10:46 UTC
Labels: pxfetcher-wip
